/**
 * Curated candidate companies for the registry builder. Each is a company
 * with a real likelihood of a public Greenhouse/Ashby/Lever board; nothing
 * here is trusted until scripts/build-registry.ts verifies it live. `tokens`
 * overrides the default slug variants when the board token is known to
 * differ from the company name.
 */
export interface Candidate {
  name: string;
  tokens?: string[];
}

export const CANDIDATES: Candidate[] = [
  // ---- AI-native ----
  { name: "Anthropic" },
  { name: "OpenAI" },
  { name: "Mistral AI", tokens: ["mistral"] },
  { name: "Cohere" },
  { name: "Hugging Face", tokens: ["huggingface"] },
  { name: "Perplexity", tokens: ["perplexity", "perplexityai", "perplexity-ai"] },
  { name: "Scale AI", tokens: ["scaleai", "scale"] },
  { name: "Runway", tokens: ["runwayml", "runway"] },
  { name: "ElevenLabs", tokens: ["elevenlabs"] },
  { name: "Character AI", tokens: ["character", "characterai"] },
  { name: "Together AI", tokens: ["togetherai", "together"] },
  { name: "Anyscale" },
  { name: "Weights & Biases", tokens: ["wandb", "weightsandbiases"] },
  { name: "Replicate" },
  { name: "Modal", tokens: ["modal", "modallabs"] },
  { name: "LangChain", tokens: ["langchain"] },
  { name: "Pinecone" },
  { name: "Weaviate" },
  { name: "Chroma", tokens: ["trychroma", "chroma"] },
  { name: "Anysphere", tokens: ["anysphere", "cursor"] },
  { name: "Sierra" },
  { name: "Harvey", tokens: ["harvey"] },
  { name: "Glean" },
  { name: "Hebbia" },
  { name: "Writer" },
  { name: "Jasper", tokens: ["jasper", "jasperai"] },
  { name: "Synthesia" },
  { name: "Luma AI", tokens: ["lumalabs", "luma"] },
  { name: "Suno" },
  { name: "xAI", tokens: ["xai", "x-ai"] },
  { name: "Groq" },
  { name: "Cerebras", tokens: ["cerebras", "cerebras-systems"] },
  { name: "SambaNova", tokens: ["sambanova", "sambanovasystems"] },
  { name: "Lambda", tokens: ["lambda", "lambdalabs", "lambdal"] },
  { name: "CoreWeave" },
  { name: "Baseten" },
  { name: "Fireworks AI", tokens: ["fireworks", "fireworksai"] },
  { name: "Deepgram" },
  { name: "AssemblyAI", tokens: ["assemblyai"] },
  { name: "Imbue" },
  { name: "Contextual AI", tokens: ["contextualai", "contextual"] },
  { name: "Codeium", tokens: ["codeium", "windsurf"] },
  { name: "Sourcegraph" },
  { name: "Poolside", tokens: ["poolside"] },
  { name: "Magic", tokens: ["magic", "magicdev", "magic-dev"] },
  { name: "Cognition", tokens: ["cognition", "cognitionai"] },
  { name: "Factory", tokens: ["factory", "factoryai"] },
  { name: "Decagon" },
  { name: "Cresta" },
  { name: "Forethought" },
  { name: "Ada", tokens: ["ada", "adasupport"] },
  { name: "Moveworks" },
  { name: "Abridge" },
  { name: "Ambience Healthcare", tokens: ["ambiencehealthcare", "ambience"] },
  { name: "Nabla" },
  { name: "OpenEvidence", tokens: ["openevidence"] },
  { name: "Photoroom", tokens: ["photoroom"] },
  { name: "Ideogram" },
  { name: "Black Forest Labs", tokens: ["blackforestlabs"] },
  { name: "Krea", tokens: ["krea"] },
  { name: "Captions" },
  { name: "HeyGen", tokens: ["heygen"] },
  { name: "Descript" },
  { name: "Gamma", tokens: ["gamma", "gammaapp"] },
  { name: "Granola" },
  { name: "Limitless", tokens: ["limitless", "rewind"] },
  { name: "Mercor" },
  { name: "Surge AI", tokens: ["surgeai", "surge"] },
  { name: "Turing" },
  { name: "Invisible Technologies", tokens: ["invisible", "invisibletech"] },
  { name: "Sakana AI", tokens: ["sakana", "sakanaai"] },
  { name: "Mistplay" },
  { name: "You.com", tokens: ["you", "youdotcom"] },

  // ---- Crypto / web3 ----
  { name: "Kraken" },
  { name: "Gemini" },
  { name: "Ripple" },
  { name: "Circle" },
  { name: "Uniswap Labs", tokens: ["uniswaplabs", "uniswap"] },
  { name: "OpenSea", tokens: ["opensea"] },
  { name: "Alchemy" },
  { name: "Chainalysis" },
  { name: "Fireblocks" },
  { name: "Ledger" },
  { name: "Consensys" },
  { name: "Solana Foundation", tokens: ["solanafoundation", "solana"] },
  { name: "Phantom" },
  { name: "Magic Eden", tokens: ["magiceden"] },
  { name: "dYdX", tokens: ["dydx"] },
  { name: "Aave", tokens: ["aave", "avaraxyz", "avara"] },
  { name: "Polygon Labs", tokens: ["polygonlabs", "polygon"] },
  { name: "StarkWare", tokens: ["starkware"] },
  { name: "Offchain Labs", tokens: ["offchainlabs"] },
  { name: "OP Labs", tokens: ["oplabs"] },
  { name: "Blockchain.com", tokens: ["blockchain", "blockchain-com"] },
  { name: "Anchorage Digital", tokens: ["anchorage", "anchoragedigital"] },
  { name: "Figment" },
  { name: "Messari" },
  { name: "Dune", tokens: ["dune", "duneanalytics"] },
  { name: "Flashbots" },
  { name: "Eigen Labs", tokens: ["eigenlabs"] },
  { name: "Chainlink Labs", tokens: ["chainlinklabs", "chainlink"] },
  { name: "Ava Labs", tokens: ["avalabs"] },
  { name: "Immutable" },
  { name: "Bitwise", tokens: ["bitwise", "bitwiseinvestments"] },
  { name: "Galaxy", tokens: ["galaxy", "galaxydigital"] },
  { name: "Paxos" },
  { name: "TRM Labs", tokens: ["trmlabs", "trm"] },
  { name: "Zora" },
  { name: "Privy" },
  { name: "Turnkey" },
  { name: "Helius" },
  { name: "Jito", tokens: ["jito", "jitolabs"] },
  { name: "LayerZero", tokens: ["layerzero", "layerzerolabs"] },
  { name: "Tools for Humanity", tokens: ["toolsforhumanity"] },
  { name: "Exodus" },
  { name: "MoonPay", tokens: ["moonpay"] },
  { name: "Bitpanda" },
  { name: "Crypto.com", tokens: ["cryptocom", "crypto-com"] },
  { name: "BitGo", tokens: ["bitgo"] },
  { name: "Falconx", tokens: ["falconx"] },
  { name: "Wintermute" },
  { name: "GSR", tokens: ["gsr"] },
  { name: "Nansen" },
  { name: "CertiK", tokens: ["certik"] },
  { name: "Trail of Bits", tokens: ["trailofbits"] },

  // ---- Fintech ----
  { name: "Stripe" },
  { name: "Plaid" },
  { name: "Ramp" },
  { name: "Brex" },
  { name: "Mercury" },
  { name: "Chime", tokens: ["chime", "chimecard"] },
  { name: "Affirm" },
  { name: "Marqeta" },
  { name: "Modern Treasury", tokens: ["moderntreasury"] },
  { name: "Unit", tokens: ["unit", "unitco"] },
  { name: "Lithic" },
  { name: "Airwallex" },
  { name: "Wise" },
  { name: "Revolut" },
  { name: "Monzo" },
  { name: "Klarna" },
  { name: "Robinhood" },
  { name: "Public", tokens: ["public", "publicapp"] },
  { name: "Wealthfront" },
  { name: "Betterment" },
  { name: "Addepar" },
  { name: "Carta" },
  { name: "AngelList", tokens: ["angellist"] },
  { name: "Pulley" },
  { name: "Deel" },
  { name: "Rippling" },
  { name: "Gusto" },
  { name: "Justworks" },
  { name: "Check", tokens: ["check", "checkhq"] },
  { name: "Column", tokens: ["column"] },
  { name: "Increase" },
  { name: "Moov", tokens: ["moov", "moovfinancial"] },
  { name: "Highnote" },
  { name: "Sardine" },
  { name: "Alloy" },
  { name: "Persona" },
  { name: "Middesk" },
  { name: "Socure" },
  { name: "Stytch" },
  { name: "Bilt Rewards", tokens: ["bilt", "biltrewards"] },
  { name: "Found" },
  { name: "Pilot", tokens: ["pilot", "pilotcom"] },
  { name: "Checkout.com", tokens: ["checkout", "checkoutcom"] },
  { name: "Paddle" },
  { name: "Melio" },
  { name: "Navan" },
  { name: "Zip", tokens: ["zip", "ziphq"] },
  { name: "Tropic" },
  { name: "Vendr" },
  { name: "Anrok" },
  { name: "Adyen" },
  { name: "Nubank" },
  { name: "N26", tokens: ["n26"] },
  { name: "Qonto" },
  { name: "Pleo" },
  { name: "Payhawk" },
  { name: "Tide" },
  { name: "Zilch" },
  { name: "GoCardless", tokens: ["gocardless"] },
  { name: "TrueLayer", tokens: ["truelayer"] },
  { name: "Codat" },
  { name: "Griffin", tokens: ["griffin", "griffinbank"] },
  { name: "Synctera" },
  { name: "Orum", tokens: ["orum", "orumio"] },
  { name: "Trust & Will", tokens: ["trustandwill"] },

  // ---- Devtools / infra ----
  { name: "GitLab" },
  { name: "Vercel" },
  { name: "Netlify" },
  { name: "Render" },
  { name: "Fly.io", tokens: ["fly", "flyio", "fly-io"] },
  { name: "Railway" },
  { name: "Supabase" },
  { name: "PlanetScale", tokens: ["planetscale"] },
  { name: "Neon", tokens: ["neon", "neondatabase"] },
  { name: "Prisma" },
  { name: "Hasura" },
  { name: "Apollo GraphQL", tokens: ["apollographql", "apollo"] },
  { name: "Kong" },
  { name: "Postman" },
  { name: "HashiCorp", tokens: ["hashicorp"] },
  { name: "Docker" },
  { name: "Pulumi" },
  { name: "Temporal", tokens: ["temporal", "temporaltechnologies"] },
  { name: "Retool" },
  { name: "Linear" },
  { name: "Notion" },
  { name: "Coda" },
  { name: "Airtable" },
  { name: "Zapier" },
  { name: "Figma" },
  { name: "Framer" },
  { name: "Webflow" },
  { name: "Canva" },
  { name: "Miro" },
  { name: "Loom" },
  { name: "Grammarly" },
  { name: "1Password", tokens: ["1password", "agilebits"] },
  { name: "Tailscale" },
  { name: "Cloudflare" },
  { name: "Fastly" },
  { name: "Sentry" },
  { name: "Honeycomb" },
  { name: "Grafana Labs", tokens: ["grafanalabs", "grafana"] },
  { name: "Chronosphere" },
  { name: "Axiom", tokens: ["axiom", "axiomco"] },
  { name: "PostHog", tokens: ["posthog"] },
  { name: "Amplitude" },
  { name: "Mixpanel" },
  { name: "Heap" },
  { name: "LaunchDarkly", tokens: ["launchdarkly"] },
  { name: "Statsig" },
  { name: "Snyk" },
  { name: "Wiz", tokens: ["wiz", "wizinc"] },
  { name: "Vanta" },
  { name: "Drata" },
  { name: "Secureframe" },
  { name: "Doppler" },
  { name: "Teleport" },
  { name: "Deno", tokens: ["deno", "denoland"] },
  { name: "Oven", tokens: ["oven", "bun"] },
  { name: "Warp", tokens: ["warp", "warpdotdev"] },
  { name: "Replit" },
  { name: "StackBlitz", tokens: ["stackblitz"] },
  { name: "Graphite", tokens: ["graphite", "graphitedev"] },
  { name: "Semgrep" },
  { name: "Socket", tokens: ["socket", "socketdev"] },
  { name: "Chainguard" },
  { name: "Dagger" },
  { name: "Buildkite" },
  { name: "CircleCI", tokens: ["circleci"] },
  { name: "Harness" },
  { name: "Convex" },
  { name: "Clerk" },
  { name: "WorkOS", tokens: ["workos"] },
  { name: "Resend" },
  { name: "Customer.io", tokens: ["customerio", "customer-io"] },
  { name: "Knock" },
  { name: "Inngest" },
  { name: "Redpanda", tokens: ["redpanda", "redpandadata"] },
  { name: "Materialize" },
  { name: "ClickHouse", tokens: ["clickhouse"] },
  { name: "Timescale" },
  { name: "InfluxData", tokens: ["influxdata"] },
  { name: "Cockroach Labs", tokens: ["cockroachlabs"] },
  { name: "SingleStore", tokens: ["singlestore"] },
  { name: "MongoDB", tokens: ["mongodb"] },
  { name: "Elastic" },
  { name: "Redis" },
  { name: "dbt Labs", tokens: ["dbtlabs", "dbtlabsinc"] },
  { name: "Fivetran" },
  { name: "Airbyte" },
  { name: "Census" },
  { name: "Hightouch" },
  { name: "Hex", tokens: ["hex", "hextechnologies"] },
  { name: "Sigma Computing", tokens: ["sigmacomputing"] },
  { name: "Metabase" },
  { name: "Preset" },
  { name: "Monte Carlo", tokens: ["montecarlo", "montecarlodata"] },
  { name: "Atlan" },
  { name: "Astronomer" },
  { name: "Prefect" },
  { name: "Dagster Labs", tokens: ["dagsterlabs", "dagster", "elementl"] },
  { name: "Databricks" },
  { name: "Confluent" },
  { name: "Starburst", tokens: ["starburst", "starburstdata"] },
  { name: "Dremio" },
  { name: "MotherDuck", tokens: ["motherduck"] },
  { name: "Algolia" },
  { name: "Meilisearch" },
  { name: "Speakeasy" },
  { name: "Mintlify" },
  { name: "ReadMe", tokens: ["readme"] },
  { name: "Stainless", tokens: ["stainless", "stainlessapi"] },
  { name: "Browserbase" },
  { name: "E2B", tokens: ["e2b"] },
  { name: "Daytona" },
  { name: "Northflank" },
  { name: "Porter", tokens: ["porter"] },
  { name: "Coder" },
  { name: "Gitpod" },
  { name: "Depot" },
  { name: "Namespace", tokens: ["namespace", "namespacelabs"] },

  // ---- Design-forward product ----
  { name: "The Browser Company", tokens: ["thebrowsercompany"] },
  { name: "Raycast" },
  { name: "Superhuman" },
  { name: "Amie" },
  { name: "Craft", tokens: ["craft", "craftdocs"] },
  { name: "Family", tokens: ["family", "familyco"] },
  { name: "Luma", tokens: ["luma", "lumahq"] },
  { name: "Partiful" },
  { name: "Retro", tokens: ["retro", "retroapp"] },
  { name: "Clay", tokens: ["clay", "clayhq"] },
  { name: "Read AI", tokens: ["readai", "read"] },
  { name: "Daylight", tokens: ["daylight", "daylightcomputer"] },
  { name: "Opal", tokens: ["opal", "opalcamera"] },
  { name: "Nothing", tokens: ["nothing", "nothingtech"] },
  { name: "Rive" },
  { name: "Spline" },
  { name: "Play", tokens: ["play", "createwithplay"] },
  { name: "Procreate" },
  { name: "Pitch" },
  { name: "Tella" },
  { name: "Screen Studio", tokens: ["screenstudio"] },
  { name: "Cap", tokens: ["cap", "capso"] },

  // ---- Consumer / marketplaces / other product ----
  { name: "Reddit" },
  { name: "Roblox" },
  { name: "Duolingo" },
  { name: "Strava" },
  { name: "AllTrails", tokens: ["alltrails"] },
  { name: "Calm" },
  { name: "Headspace" },
  { name: "Whoop", tokens: ["whoop"] },
  { name: "Oura", tokens: ["oura", "ouraring"] },
  { name: "Eight Sleep", tokens: ["eightsleep"] },
  { name: "Substack" },
  { name: "Patreon" },
  { name: "SoundCloud", tokens: ["soundcloud"] },
  { name: "Pinterest" },
  { name: "Turo" },
  { name: "Lime" },
  { name: "Faire" },
  { name: "Whatnot" },
  { name: "StockX", tokens: ["stockx"] },
  { name: "GOAT Group", tokens: ["goat", "goatgroup"] },
  { name: "Etsy" },
  { name: "Klaviyo" },
  { name: "Attentive" },
  { name: "Postscript" },
  { name: "Gorgias" },
  { name: "Intercom" },
  { name: "Front" },
  { name: "Lattice" },
  { name: "Culture Amp", tokens: ["cultureamp"] },
  { name: "Ashby", tokens: ["ashby", "ashbyhq"] },
  { name: "Greenhouse", tokens: ["greenhouse"] },
  { name: "Cash App", tokens: ["cashapp"] },
  { name: "Block", tokens: ["block"] },
  { name: "Squarespace" },
  { name: "Vimeo" },
  { name: "Dropbox" },
  { name: "Asana" },
  { name: "Box" },
  { name: "Twilio" },
  { name: "Okta" },
  { name: "Datadog" },
  { name: "Twitch" },
  { name: "Instacart" },
  { name: "DoorDash", tokens: ["doordash", "doordashusa"] },
  { name: "Lyft" },
  { name: "Airbnb" },
  { name: "Coursera" },
  { name: "Udemy" },
  { name: "Quizlet" },
  { name: "Khan Academy", tokens: ["khanacademy"] },
  { name: "Outschool" },

  // ---- Hard tech / aerospace / defense-adjacent ----
  { name: "SpaceX", tokens: ["spacex"] },
  { name: "Anduril", tokens: ["andurilindustries", "anduril"] },
  { name: "Shield AI", tokens: ["shieldai"] },
  { name: "Skydio" },
  { name: "Zipline", tokens: ["flyzipline", "zipline"] },
  { name: "Relativity Space", tokens: ["relativity", "relativityspace"] },
  { name: "Astranis" },
  { name: "Varda", tokens: ["varda", "vardaspace"] },
  { name: "Stoke Space", tokens: ["stokespace", "stoke"] },
  { name: "Hadrian", tokens: ["hadrian", "hadrianautomation"] },
  { name: "Applied Intuition", tokens: ["appliedintuition"] },
  { name: "Aurora Innovation", tokens: ["aurora", "aurorainnovation"] },
  { name: "Nuro" },
  { name: "Kodiak Robotics", tokens: ["kodiak", "kodiakrobotics"] },
  { name: "Saronic" },
  { name: "Figure", tokens: ["figure", "figureai"] },
  { name: "Physical Intelligence", tokens: ["physicalintelligence"] },
  { name: "Skild AI", tokens: ["skild", "skildai"] },
  { name: "1X Technologies", tokens: ["1x"] },
  { name: "Boston Dynamics", tokens: ["bostondynamics"] },

  // ---- Health / bio-adjacent ----
  { name: "Ro", tokens: ["ro", "roman"] },
  { name: "Function Health", tokens: ["functionhealth", "function"] },
  { name: "Levels", tokens: ["levels", "levelshealth"] },
  { name: "Color", tokens: ["color", "colorgenomics"] },
  { name: "Benchling" },
  { name: "Komodo Health", tokens: ["komodohealth"] },
  { name: "Maven Clinic", tokens: ["mavenclinic", "maven"] },
  { name: "Spring Health", tokens: ["springhealth"] },
  { name: "Headway" },
  { name: "Alma", tokens: ["alma", "helloalma"] },
  { name: "Rula" },
  { name: "Tennr" },
  { name: "Anterior" },

  // ---- Enterprise SaaS / security ----
  { name: "Ironclad" },
  { name: "Everlaw" },
  { name: "Docusign", tokens: ["docusign"] },
  { name: "PandaDoc", tokens: ["pandadoc"] },
  { name: "Smartsheet" },
  { name: "Guru", tokens: ["guru", "getguru"] },
  { name: "Slab" },
  { name: "Abnormal Security", tokens: ["abnormalsecurity", "abnormal"] },
  { name: "Material Security", tokens: ["materialsecurity"] },
  { name: "Tines" },
  { name: "Torq" },
  { name: "Island", tokens: ["island"] },
  { name: "Tanium" },
  { name: "Arctic Wolf", tokens: ["arcticwolf"] },
  { name: "Huntress" },
  { name: "Expel" },
  { name: "Red Canary", tokens: ["redcanary"] },
  { name: "Orca Security", tokens: ["orcasecurity", "orca"] },
  { name: "Lacework" },
  { name: "Sysdig" },
  { name: "Cribl" },
  { name: "Observe", tokens: ["observe", "observeinc"] },
  { name: "Verkada" },
  { name: "Samsara" },
  { name: "Motive", tokens: ["motive", "gomotive"] },
  { name: "ServiceTitan", tokens: ["servicetitan"] },
  { name: "Procore" },
  { name: "EquipmentShare", tokens: ["equipmentshare"] },
];
